### ISSUE TITLE
Why `restart nfs` instead of `exportfs`?

### ISSUE THREAD

**Issue by danschmidt5189** [geerlingguy/ansible-role-nfs#21]
RedHat's documentation is, admittedly, a little [light on reasoning](https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/7/html/storage_administration_guide/nfs-serverconfig), but they seem to suggest that changes to `/etc/exports` should be handled by running `exportfs -ar` instead of restarting nfsd:

- exportfs syncs current exports without restarting nfs
- Restarting NFS reloads /etc/exports _and also_ /etc/sysconfig/nfs

I'm not entirely clear on the client impact, but it seems preferable to keep the nfs server running during the config update, and able to negotiate with clients. In pseudocode (or rather, borrowed from one of my roles…) the new handlers would look something like:

```yml
- name: Re-export all shared directories
  command: /usr/sbin/exportfs -r -a
  listen:
    - nfs__event__export_directory_created
    - nfs__event__exports_reconfigured

- name: Restart NFS
  service:
    name: "{{ nfs__service_name }}"
    state: restarted
  listen:
    - nfs__event__nfsd_reconfigured
```

What are your thoughts on this?
